[ -f ~/.zshrc.aliases ] && source ~/.zshrc.aliases
# [ -f ~/.zshrc.general ] && source ~/.zshrc.general
#[ -f ~/.zshrc.private ] && source ~/.zshrc.private

#basis
#export LANG=ja_JP.UTF-8
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#Complement command and its options
#jutoload -Uz compinit
#compinit

#z command installation rupa/github
.

source ~/.zsh_profile
#oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

#plugins
plugins=(git)
PATH=/usr/local/bin:$PATH
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#Vi key bind
bindkey -e

alias be='bundle exec'
